language: bash

before_script:
  - curl -L "https://github.com/kward/shunit2/archive/source.tar.gz" | tar zx

install:
  - git clone https://github.com/kepbod/pl.git $HOME/pl
  - export PERLLIB="$HOME/pl:$PERLLIB"


script:
  - bash test.sh
